name: Main workflow

on:
  push:
    paths-ignore:
      - "**.md"
      - ".all-contributorsrc"
  pull_request:
    paths-ignore:
      - "**.md"
      - ".all-contributorsrc"

jobs:
  plugin_test:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1.0.0
        with:
          command: "emcc --version"
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }} # automatically provided
