language: bash
script: asdf plugin-test rabbitmq https://github.com/w-sanches/asdf-rabbitmq.git
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
os:
  - linux
  - osx
