language: c
os:
  - linux
  - osx
before_script:
  - git clone https://github.com/asdf-vm/asdf.git asdf
  - . asdf/asdf.sh
script:
  - asdf plugin-add jsonnet ./
  - asdf list-all jsonnet
  - asdf plugin-test jsonnet ./ 'jsonnet --version'
