language: c
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
script:
  - asdf plugin-add sops ./
  - asdf list-all sops
  - asdf plugin-test sops ./ 'sops --version'
os:
  - osx

