language: c
script:
  - asdf plugin-test swi-prolog $TRAVIS_BUILD_DIR 'swipl --version'
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
os:
  - linux
  - osx
osx_image: xcode11

addons:
  homebrew:
    packages:
      - readline
      - libarchive
  apt:
    packages:
      - libxinerama-dev
      - libarchive-dev
