name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout asdf
        uses: actions/checkout@v2
        with:
          repository: asdf-vm/asdf
          path: asdf
      - name: test plugin
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: tilt version
        env:
          OAUTH_TOKEN: ${{ github.token }}
