language: c
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
script:
  - bin/list-all
  - asdf plugin-add kubesec ./
  - asdf list-all kubesec
  - asdf plugin-test kubesec ./
os:
  - linux
  - osx
