name: Build
on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    paths-ignore:
      - "**.md"
  schedule:
    - cron: "0 0 * * *" # daily at midnight

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      # - name: asdf_install
      #   uses: asdf-vm/actions/install@v1
      #   with:
      #     tool_versions: postgres 13.1
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: ls -l # pg_tmp -w 1 should work, but asdf isn't reshimming the postgres dependency
