---
name: CI

on: push

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bats:
    strategy:
      matrix:
        runner:
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: ghcup nuke
      - run: ./test/bats/bin/bats -T test

  plugin_test:
    strategy:
      matrix:
        runner:
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.runner }}
    steps:
      - uses: asdf-vm/actions/plugin-test@v2
        with:
          plugin: ghc
          command: ghc --version

  release:
    runs-on: ubuntu-latest
    needs:
      - bats
      - plugin_test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm
      - run: npm install
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
