name: CI

on: [push]

jobs:
  test:
    name: Test ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [x64]
    steps:
      - uses: actions/checkout@v2
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: "./shims/julia --version"
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
